#!/bin/bash
sctl='/home/qfpay/superctl'

start () {
    $sctl start maxscale && return 0 || return 1
}

stop () {
    $sctl stop maxscale && return 0 || return 1
}

status () {
    /home/qfpay/mariadb/bin/mysql -h127.0.0.1 -utest -ptest -e "select 1;" > /dev/null
    ret=$?
    if [ $ret -eq 0 ]
    then
        return 0
    else
        return 1
    fi
}

case "$1" in
    start)
        start
        status
    ;;
    stop)
        stop
    ;;
    status)
        status
    ;;
    restart)
        stop
        start
    ;;
esac
